version: 0.2

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install default-jdk
      - apt-get install -y maven
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - '**/*'
