version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y  maven
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - '**/*'
